name: guppy build

on:
  push:
    branches: [ "dev_workflow" ]
  pull_request:
    branches: [ "dev_workflow" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    container: ballaswag/guppydev:latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
    - run: |
        echo "CROSS_COMPILE=mips-linux-gnu-" >> $GITHUB_ENV
    - name: make wpaclient
      run: make wpaclient
    - name: make libhv
      run: make libhv.a
    - name: make guppyscreen
      run: make -j
