name: guppy build

on:
  push:
    branches: [ "dev_workflow" ]
  pull_request:
    branches: [ "dev_workflow" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    container: ballaswag/guppydev:latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - run: |
        echo "CROSS_COMPILE=mips-linux-gnu-" >> $GITHUB_ENV
    - name: patch lv_drivers
    - working-directory: ./lv_drivers
    - run: |
        git apply ../patches/0001-lv_driver_fb_ioctls.patch
    - name: patch fmt in spdlog
    - working-directory: ./spdlog
    - run: |
        git apply ../patches/0002-spdlog_fmt_initializer_list.patch
    - name: make wpaclient
      run: make wpaclient
    - name: make libhv
      run: make libhv.a
    - name: make guppyscreen
      run: make -j
    - uses: actions/upload-artifact@v4
      with:
        name: guppyscreen
        path: build/bin/guppyscreen
